export const ADD_POST = 'ADD_POST'
export const DELETE_POST = 'DELETE_POST'
export const SET_CURRENT = 'SET_CURRENT'
export const CLEAR_CURRENT = 'CLEAR_CURRENT'
export const UPDATE_POST = 'UPDATE_POST'
export const FILTER_POST = 'FILTER_POST'
export const CLEAR_FILTER = 'CLEAR_FILTER'